### ISSUE TITLE
Add teamonly to gameevent `player_say`

### ISSUE THREAD

**Issue by ANormalTwig** [Facepunch/garrysmod-requests#2276]
### Details
its already available to [where the event is called from](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/client.cpp#L347-L354)

**Comment by robotboy655** [comment]
Done.

**Comment by RaphaelIT7** [comment]
I think you forgot to add it to the `resource/serverevents.res` file.
Because of this the `teamonly` field won't be networked?
```
	"player_say"
	{
		"userid"	"short"		// user ID on server
		"text"		"string"	// the say text
		"teamonly"	"bool"		// is it teamonly <-- This line needs to be added
	}
```
Or is it intentional that it's only serverside?

**Comment by robotboy655** [comment]
No I did not, but you can open a separate issue for that if you really need to.
